#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn inject-readme-markdown \
&& git add README.md && git add packages/core/README.md && git add packages/react/README.md \
&& yarn pretty-quick --staged \
&& yarn lint-staged
